# Generated by Django 3.0.8 on 2020-07-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_partner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('send_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
