# Generated by Django 3.0.8 on 2020-07-25 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_partner', '0003_auto_20200725_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagesofhotels',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelimage', to='hotel_partner.HotelPartners'),
        ),
    ]
