# Generated by Django 3.0.8 on 2020-07-27 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_partner', '0005_extramodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extramodel',
            name='hotel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_name', to='hotel_partner.HotelPartners'),
        ),
    ]
