# Generated by Django 3.0.8 on 2020-08-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_partner', '0007_auto_20200728_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
